### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by anderskitson** [themeteorchef/uploading-files-to-amazon-s3#2]
I get the following error on my server but not on my local host

```
Error: You are not allowed to upload this file [Unauthorized]
    at [object Object].Meteor.methods.slingshot/uploadRequest (packages/edgee_slingshot/packages/edgee_slingshot.js:421:1)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:707:46
    at tryCallTwo (/bundle/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/bundle/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:200:13)
    at new Promise (/bundle/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:66:3)
    at Session.method (packages/ddp-server/livedata_server.js:681:23)
    at packages/meteorhacks_kadira/lib/hijack/wrap_session.js:52:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Session.sessionProto.protocol_handlers.method (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:51:1)
    at packages/ddp-server/livedata_server.js:551:43
```

**Comment by ababba15** [comment]
I started getting it too for unknown reason.

**Comment by themeteorchef** [comment]
This is most likely a region issue with the Amazon S3 bucket. A potential fix is to figure out what region your bucket is in and find the correct region name [in this list](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) (the Region column). Next, in your Slingshot directive add a `region` property like this with that value:

``` javascript
Slingshot.createDirective("blurpadurpadoo", Slingshot.S3Storage, {
  region: "us-east-1",
  [...]
});
```

Let me know if that works :)

**Comment by qrobin** [comment]
@themeteorchef it works, I have fixed it exactly the way that you have provided.

**Comment by themeteorchef** [comment]
Great :)

**Comment by pagesrichie** [comment]
I'm actually running into this issue, and I have the correct region...
